### PR TITLE
Support `bpmn:timeDate` for Timer Boundary and Intermediate Catch Events

### PR DESCRIPTION
**Pull request by philippfromme**
Related to https://github.com/camunda/camunda-modeler/issues/3516

### CODE REVIEW

**Comment by nikku** [comment]
@philippfromme CI is failing. Are you aware?

**Comment by nikku** [comment]
Making DRAFT until CI is fixed.

**Comment by philippfromme** [comment]
Ready for review.

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
@philippfromme Please go ahead and release + integrate this.

**Pull request merged**
